
-- Add missing columns to company_project table for better project management
ALTER TABLE public.company_project 
ADD COLUMN IF NOT EXISTS preference_number integer DEFAULT 999,
ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS project_summary text,
ADD COLUMN IF NOT EXISTS budget_range text,
ADD COLUMN IF NOT EXISTS roi_metrics jsonb,
ADD COLUMN IF NOT EXISTS testimonial_quote text,
ADD COLUMN IF NOT EXISTS testimonial_author text,
ADD COLUMN IF NOT EXISTS testimonial_position text;

-- Insert 4 demo projects with comprehensive details
INSERT INTO public.company_project (
  title, 
  description, 
  short_description,
  full_description,
  project_summary,
  image_url, 
  client_name, 
  industry, 
  project_status, 
  team_size, 
  duration_months,
  start_date,
  end_date,
  budget_range, 
  technologies_used, 
  key_features, 
  challenges_solved, 
  impact_metrics,
  roi_metrics,
  testimonial_quote,
  testimonial_author,
  testimonial_position,
  preference_number,
  is_featured
) VALUES 
(
  'Smart City Traffic Management System',
  'AI-powered traffic optimization system reducing congestion by 40% across metropolitan areas.',
  'Revolutionary AI system that optimizes traffic flow in real-time.',
  'Our Smart City Traffic Management System represents a breakthrough in urban mobility solutions. Using advanced machine learning algorithms and IoT sensors, the system analyzes traffic patterns in real-time and dynamically adjusts signal timing, route recommendations, and congestion management strategies. The solution integrates with existing infrastructure while providing a scalable platform for future smart city initiatives.',
  'Reduced traffic congestion by 40% and improved emergency response times by 25% in major metropolitan area.',
  '/lovable-uploads/d5ddd61f-899e-4acf-a773-b03d953ab99f.png',
  'Metropolitan City Council',
  'Government & Smart Cities',
  'completed',
  15,
  18,
  '2022-01-15',
  '2023-07-15',
  '$2.5M - $5M',
  ARRAY['React', 'Python', 'TensorFlow', 'IoT Sensors', 'AWS', 'PostgreSQL', 'Redis'],
  ARRAY['Real-time traffic analysis', 'Predictive congestion modeling', 'Emergency vehicle prioritization', 'Mobile app integration', 'Dashboard analytics'],
  ARRAY['Traffic congestion reduction', 'Emergency response optimization', 'Environmental impact reduction', 'Citizen satisfaction improvement'],
  '{"congestion_reduction": "40%", "response_time_improvement": "25%", "fuel_savings": "30%", "citizen_satisfaction": "85%"}'::jsonb,
  '{"cost_savings": "$12M annually", "roi": "480%", "payback_period": "14 months"}'::jsonb,
  'This system transformed our city''s traffic management. The 40% reduction in congestion has improved quality of life for millions of residents.',
  'Sarah Johnson',
  'Director of Transportation',
  1,
  true
),
(
  'Healthcare Data Analytics Platform',
  'Comprehensive healthcare analytics platform improving patient outcomes and operational efficiency.',
  'AI-driven platform enhancing healthcare delivery through advanced analytics.',
  'Our Healthcare Data Analytics Platform revolutionizes healthcare delivery by providing comprehensive insights into patient care, operational efficiency, and clinical outcomes. The platform integrates data from multiple sources including EHRs, medical devices, and administrative systems to provide actionable insights for healthcare providers. Advanced machine learning algorithms identify patterns in patient data to support clinical decision-making and predict health risks.',
  'Improved patient outcomes by 35% and reduced operational costs by 28% across 50+ healthcare facilities.',
  '/lovable-uploads/d5ddd61f-899e-4acf-a773-b03d953ab99f.png',
  'Regional Healthcare Network',
  'Healthcare & Medical',
  'completed',
  12,
  14,
  '2022-03-01',
  '2023-05-01',
  '$1.8M - $3M',
  ARRAY['Vue.js', 'Python', 'Apache Spark', 'TensorFlow', 'Azure', 'MongoDB', 'FHIR'],
  ARRAY['Predictive analytics', 'Real-time monitoring', 'Clinical decision support', 'Population health insights', 'Compliance reporting'],
  ARRAY['Patient outcome improvement', 'Cost reduction', 'Workflow optimization', 'Risk prediction', 'Regulatory compliance'],
  '{"patient_outcome_improvement": "35%", "cost_reduction": "28%", "efficiency_gain": "45%", "readmission_reduction": "22%"}'::jsonb,
  '{"annual_savings": "$8.5M", "roi": "340%", "payback_period": "18 months"}'::jsonb,
  'The analytics platform has been game-changing for our network. We''ve seen significant improvements in both patient care and operational efficiency.',
  'Dr. Michael Chen',
  'Chief Medical Officer',
  2,
  true
),
(
  'Financial Risk Assessment AI',
  'Advanced AI system for real-time financial risk assessment and fraud detection.',
  'Cutting-edge AI solution protecting financial institutions from fraud and risk.',
  'Our Financial Risk Assessment AI system provides comprehensive protection for financial institutions through advanced machine learning algorithms that analyze transaction patterns, user behavior, and market data in real-time. The system can detect fraudulent activities within milliseconds while minimizing false positives that could impact customer experience. The platform includes predictive analytics for credit risk assessment, market volatility analysis, and regulatory compliance monitoring.',
  'Reduced fraud losses by 60% and improved risk assessment accuracy by 45% for major financial institution.',
  '/lovable-uploads/d5ddd61f-899e-4acf-a773-b03d953ab99f.png',
  'Global Financial Services Corp',
  'Banking & Finance',
  'completed',
  18,
  16,
  '2022-06-01',
  '2023-10-01',
  '$3M - $5M',
  ARRAY['React', 'Python', 'Apache Kafka', 'TensorFlow', 'AWS', 'Elasticsearch', 'Docker'],
  ARRAY['Real-time fraud detection', 'Risk scoring algorithms', 'Behavioral analysis', 'Regulatory compliance', 'API integration'],
  ARRAY['Fraud prevention', 'Risk assessment accuracy', 'Regulatory compliance', 'Customer experience optimization'],
  '{"fraud_reduction": "60%", "risk_accuracy_improvement": "45%", "processing_speed": "99.9%", "false_positive_reduction": "55%"}'::jsonb,
  '{"fraud_savings": "$25M annually", "roi": "620%", "payback_period": "10 months"}'::jsonb,
  'This AI system has revolutionized our risk management capabilities. The fraud detection accuracy is phenomenal.',
  'Robert Williams',
  'Chief Risk Officer',
  3,
  true
),
(
  'E-Commerce Personalization Engine',
  'AI-powered personalization platform increasing sales conversion and customer engagement.',
  'Advanced personalization engine driving e-commerce growth through AI.',
  'Our E-Commerce Personalization Engine leverages advanced machine learning to deliver highly personalized shopping experiences that drive conversion and customer loyalty. The platform analyzes customer behavior, purchase history, browsing patterns, and demographic data to provide real-time product recommendations, dynamic pricing, and personalized content. The system integrates seamlessly with existing e-commerce platforms and provides comprehensive analytics for continuous optimization.',
  'Increased conversion rates by 55% and customer lifetime value by 40% for leading e-commerce platform.',
  '/lovable-uploads/d5ddd61f-899e-4acf-a773-b03d953ab99f.png',
  'E-Commerce Solutions Inc',
  'Retail & E-Commerce',
  'completed',
  10,
  12,
  '2022-08-01',
  '2023-08-01',
  '$1.2M - $2.5M',
  ARRAY['Next.js', 'Python', 'Apache Spark', 'TensorFlow', 'GCP', 'BigQuery', 'Kubernetes'],
  ARRAY['Real-time recommendations', 'Dynamic pricing', 'Customer segmentation', 'A/B testing framework', 'Analytics dashboard'],
  ARRAY['Conversion rate optimization', 'Customer retention', 'Revenue growth', 'User experience enhancement'],
  '{"conversion_increase": "55%", "customer_lifetime_value": "40%", "revenue_growth": "32%", "engagement_improvement": "48%"}'::jsonb,
  '{"revenue_increase": "$15M annually", "roi": "750%", "payback_period": "8 months"}'::jsonb,
  'The personalization engine has transformed our business. Customer engagement and sales have reached unprecedented levels.',
  'Lisa Anderson',
  'VP of Digital Commerce',
  4,
  false
);
