// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppveueulvmkykdbaaenz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdmV1ZXVsdm1reWtkYmFhZW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDYwMDksImV4cCI6MjA2NDE4MjAwOX0.64U3Y6vhJy3gOK04zhOHlRyZiB_K3pN4yZJKvNs1urc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);